"use strict";
var sys_service_js_1 = require('./sys.service.js');
exports.SysService = sys_service_js_1.SysService;
var collections_service_js_1 = require('./collections.service.js');
exports.CollectionsService = collections_service_js_1.CollectionsService;
var auth_service_js_1 = require('./auth.service.js');
exports.AuthService = auth_service_js_1.AuthService;
var language_service_js_1 = require('./language.service.js');
exports.LanguageService = language_service_js_1.LanguageService;
var services_module_js_1 = require('./services.module.js');
exports.SysServicesModule = services_module_js_1.SysServicesModule;
